#!/bin/bash

echo "running script $0..."
# 脚本说明：推送本地commit到origin/master，然后上传操作日志。
echo "\$0:$0"
echo "\$1:$1"
targetDir=$1

shellDir=$(dirname $0)
echo -e "shellDir:$shellDir\npwd:$(pwd)"

exit_if_target_dir_not_exit () {
	echo "exit_if_target_dir_not_exit..."
	dir=$1
	if [ ! -d "$dir" ]; then
  		echo "目录($dir)不存在，即将退出处理..."
  		exit -1
	fi
}



main() {
	exit_if_target_dir_not_exit "$targetDir"
	
	cd "$shellDir"
	sh .inner_tools/git_push "$targetDir" >> "$targetDir"/.syn.log 2>&1
	
	cd $shellDir
	sh .inner_tools/upload_log "$targetDir"
}

main


