#!/bin/bash
echo "running script $0..."


echo "\$0:$0"
echo "\$1:$1"
targetDir="$1"

get_current_date (){
	echo $(date '+%Y-%m-%d %H:%M:%S')
}

push_stash () {
	echo "git stash push..." 
	git stash push
}

pop_stash () {
	echo "git stash pop..." 
	git stash pop
}

# batch_sh 批量同步命令（给crontab用）
stash_and_pull(){
	echo "git stash push..."
	git add *
	git add .
	git rm $(git ls-files --deleted)
	git stash push
	echo "git pull..."
	git pull
	echo "git stash pop..."
	git stash pop
}

exit_if_target_dir_not_exit () {
	echo "exit_if_target_dir_not_exit..."
	dir=$1
	if [ ! -d "$dir" ]; then
  		echo "目录($dir)不存在，即将退出处理..."
  		exit -1
	fi
}



main () {
	exit_if_target_dir_not_exit "$targetDir"

	echo "---------------🔻🔻🔻🔻🔻 目标仓库：$targetDir 🔻🔻🔻🔻 ----------------"

	echo "---------------🔻🔻🔻🔻🔻 pull 开始执行[$(get_current_date)] 🔻🔻🔻🔻 ----------------"

	cd "$targetDir"
	stash_and_pull

	echo "---------------🔻🔻🔻🔻🔻 目标仓库：$targetDir 🔻🔻🔻🔻 ----------------"
	echo  "--------------- 🔻🔻🔻🔻 pull 执行结束时间[$(get_current_date)] 🔻🔻🔻🔻 ----------------"
	echo ""
}


# =============== main =============== 
main
# =============== main =============== 

